### ISSUE TITLE
End of RAMP to do

### ISSUE THREAD

**Issue by claireh93** [ScottishCovidResponse/SCRCIssueTracking#654]
A few priorities for the last few weeks of the RAMP period:

## Musts

- [x] Data being pulled in from the pipeline using SimulationData. https://github.com/ScottishCovidResponse/Simulation.jl/pull/67

- [ ] Deterministic version of the model used for internal testing. @jwscook https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/681 & https://github.com/ScottishCovidResponse/Simulation.jl/pull/68

- [ ] Code coverage - delete vestigial code, refactor & some new tests. https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/682

- [x] Commuter data and lockdown. https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/475

- [x] Either an integration test or an example in `Epidemiology` of both reading from the pipeline and writing back to it. https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/678 . Tick off when https://github.com/ScottishCovidResponse/Simulation.jl/pull/72 closes.

- [x] Write up TODOs in order to complete work on Axis Arrays https://github.com/ScottishCovidResponse/Simulation.jl/pull/54

- [x] Tidy up open PRs

## Nice to haves

- [ ] We need for all the data/params required by Simulation.jl to be uploaded to data pipeline.

- [x] Updated docs 

- [x] Add scorecard .md file

**Comment by sdl1** [comment]
> Data being pulled in from the pipeline using SimulationData.

This has three main steps I think, we should be close to getting them all done:

- [x] https://github.com/ScottishCovidResponse/SimulationData.jl/pull/12
- [x] then https://github.com/ScottishCovidResponse/Simulation.jl/pull/67
- [x] then try loading some real data from the actual repo
