### ISSUE TITLE
End-to-end run of BEEPmbp through data pipeline

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#670]
We want to:
- [ ] Get real or dummy data into the repository in a format that BEEPmbp can read - see #677 
- [ ] Download the data using the download script
- [ ] Read all data and priors from the data pipeline during a BEEPmbp run using the C++ wrapper of the Python data pipeline API - see #366
- [ ] Write results from BEEPmbp to the data pipeline during the run - see #367 
- [ ] Upload the results using the upload script
